### ISSUE TITLE
Use motion controls over DSU protocol?

### ISSUE THREAD

**Issue by Phantop** [moslevin/netstick-3ds#2]
The majority of emulators use the DSU protocol for easy addition of motion controls. There's no clear way to add netstick's gyroscope to, say, Dolphin emulator. Implementing this protocol, or allowing a direct way of adding it, would be very appreciated.

**Comment by moslevin** [comment]
Interesting -- I'll have to think about how I'd go about adding this, since DSU is a pretty different protocol from Netstick.  I'll have to see what's out there in terms of linux DSU wrappers, and see if there's anything I could adapt without having to explicit add support for it in the client/server side.  Otherwise, it might be reasonable to look into adding a separate DSU client implementation on the 3DS directly.
